"""Shared SmbOS helpers: directory resolution, frontmatter, SOP iteration, run log.

The canonical implementations; scripts import from here instead of re-rolling.
Stdlib only, Python 3.9+ (the macOS system python that Claude Desktop uses).
"""
import hashlib
import json
import os
import re
import secrets
import shutil
import stat
import sys
import time
from datetime import date, datetime, timezone
from pathlib import Path

SKIP_NAMES = {"INDEX.md", "_template.md", "DIGEST.md"}  # DIGEST.md is generated by digest.py
# Directories under the SOP root that hold runtime state, never SOPs.
RUNTIME_DIRS = {"pending", "payloads", "triggers", "queue", "work", "active-runs"}
ARCHIVE_DIR = "archive"
NOTES_HEADING = "## Notes for next revision"  # where a dashboard suggestion is appended in an SOP


def resolve_sop_dir(explicit=None, use_cwd=False, exit_on_missing=True):
    """argv-style explicit > $SOP_DIR > (optionally ./sops) > ~/sops."""
    candidates = [explicit, os.environ.get("SOP_DIR")]
    if use_cwd:
        candidates.append(str(Path.cwd() / "sops"))
    candidates.append(str(Path.home() / "sops"))
    for c in candidates:
        if c and Path(c).expanduser().is_dir():
            return Path(c).expanduser()
    if exit_on_missing:
        sys.exit("No SOP directory found (checked explicit, $SOP_DIR, ~/sops).")
    return None


def parse_frontmatter(text):
    """Return the frontmatter dict from a markdown document ('' values stripped)."""
    meta = {}
    m = re.match(r"^---\r?\n(.*?)\r?\n---", text, re.S)
    if m:
        for line in m.group(1).splitlines():
            if ":" in line and not line.lstrip().startswith("#"):
                k, _, v = line.partition(":")
                meta[k.strip()] = v.strip()
    return meta


def split_frontmatter(text):
    """Return (meta dict, body) for a markdown document."""
    m = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n?(.*)$", text, re.S)
    if not m:
        return {}, text
    meta = parse_frontmatter(text)
    return meta, m.group(2)


# Sections that are journals about the procedure, not the procedure itself.
# Excluded from the fingerprint so dashboard suggestions and changelog lines
# never read as unrecorded changes.
_JOURNAL_SECTIONS = ("Notes for next revision", "Changelog")


# Frontmatter fields that grant capabilities to background runs. They MUST be
# inside the fingerprint: the stamp is what makes them owner-sanctioned, and a
# body-only hash would let an out-of-band edit widen the allowlist of an
# already-stamped SOP without tripping the drift gate.
CAPABILITY_FIELDS = ("research_domains", "research_reads", "deliverable")


def content_fingerprint(body, meta=None):
    """Hash of the procedure: body (journal sections stripped, line endings
    normalized) plus the capability-granting frontmatter fields."""
    text = body.replace("\r\n", "\n")
    for name in _JOURNAL_SECTIONS:
        text = re.sub(rf"^## {re.escape(name)}\n.*?(?=^## |\Z)", "", text, flags=re.M | re.S)
    m = meta or {}
    caps = "\n".join(f"{k}={m.get(k, '')}" for k in CAPABILITY_FIELDS)
    # interactive_only is capability-bearing (it gates the unattended runner),
    # so fold it into the fingerprint to make stripping it out-of-band trip
    # drift detection. Append only when set, so adding this never re-fingerprints
    # the existing stamped SOPs that don't carry the flag.
    if str(m.get("interactive_only", "")).strip().lower() in ("true", "yes", "1"):
        caps += "\ninteractive_only=true"
    return hashlib.sha256((caps + "\n" + text.strip()).encode("utf-8")).hexdigest()[:12]


def is_drifted(meta, body):
    """True when the body no longer matches the recorded fingerprint.

    A missing fingerprint is "unstamped", not drift: existing libraries
    stay quiet until their SOPs are stamped or bumped.
    """
    recorded = meta.get("content_hash")
    return bool(recorded) and recorded != content_fingerprint(body, meta)


def set_frontmatter_fields(text, updates):
    """Upsert frontmatter fields, preserving order; new fields go before the closing ---."""
    m = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n?(.*)$", text, re.S)
    if not m:
        raise ValueError("document has no frontmatter")
    lines = m.group(1).splitlines()
    pending = dict(updates)
    for i, line in enumerate(lines):
        k = line.partition(":")[0].strip()
        if k in pending:
            lines[i] = f"{k}: {pending.pop(k)}"
    lines += [f"{k}: {v}" for k, v in pending.items()]
    return "---\n" + "\n".join(lines) + "\n---\n" + m.group(2)


def frontmatter_field(path, field, head_bytes=1000):
    """Read one frontmatter field from a file without parsing the whole document."""
    head = Path(path).read_text(encoding="utf-8")[:head_bytes]
    m = re.search(rf"^{re.escape(field)}: *(.+)$", head, re.M)
    return m.group(1).strip() if m else None


def iter_sops(sop_dir, include_archive=False):
    """Yield SOP file paths, skipping runtime dirs, index, template, dotfiles."""
    skip = set(RUNTIME_DIRS) if include_archive else set(RUNTIME_DIRS) | {ARCHIVE_DIR}
    for p in sorted(Path(sop_dir).rglob("*.md")):
        rel = p.relative_to(sop_dir)
        if p.name in SKIP_NAMES or p.name.startswith(".") or any(d in skip for d in rel.parts):
            continue
        yield p


def find_sop(sop_dir, sop_id):
    """Find an SOP by filename stem or frontmatter id; None if absent."""
    for p in iter_sops(sop_dir):
        if p.stem == sop_id:
            return p
        if frontmatter_field(p, "id") == sop_id:
            return p
    return None


def read_runs(sop_dir):
    """Parse runs.jsonl into a list of dicts, skipping malformed lines."""
    log = Path(sop_dir) / "runs.jsonl"
    out = []
    if log.exists():
        for line in log.read_text(encoding="utf-8").splitlines():
            try:
                out.append(json.loads(line))
            except ValueError:
                continue
    return out


def month_spend(sop_dir):
    """Sum cost_usd of this calendar month's runs."""
    prefix = date.today().strftime("%Y-%m")
    total = 0.0
    for r in read_runs(sop_dir):
        if str(r.get("ts", "")).startswith(prefix):
            try:
                total += float(r.get("cost_usd") or 0)
            except (TypeError, ValueError):
                continue
    return total


def _terminal_notifier():
    """Locate terminal-notifier even under a minimal PATH. run_sop's dashboard-launched runs
    and the launchd/cron digest both get a bare PATH, so shutil.which alone misses a brew
    install; fall back to the two standard brew prefixes so the click target works there too."""
    found = shutil.which("terminal-notifier")
    if found:
        return found
    for cand in ("/opt/homebrew/bin/terminal-notifier", "/usr/local/bin/terminal-notifier"):
        if os.path.exists(cand):
            return cand
    return None


def notify(title, body, open_url=None):
    """macOS notification; silent no-op elsewhere and on any failure.

    Prefers terminal-notifier when installed: it lets a click open `open_url` (the dashboard),
    instead of osascript's `display notification`, which macOS attributes to Script Editor and
    launches it on click (no way to set a click target). Falls back to osascript when
    terminal-notifier is absent, so notifications still appear, just without the useful click.
    """
    if sys.platform != "darwin":
        return False
    try:
        import subprocess
        tn = _terminal_notifier()
        if tn:
            # No -group: each notification is independent, so a later "needs attention" never
            # silently replaces an unseen "result waiting" in Notification Center.
            cmd = [tn, "-title", str(title), "-message", str(body)]
            if open_url:
                cmd += ["-open", str(open_url)]  # click opens the dashboard
            return subprocess.run(cmd, capture_output=True, timeout=10).returncode == 0
        esc = lambda s: str(s).replace("\\", "\\\\").replace('"', '\\"')
        done = subprocess.run(["/usr/bin/osascript", "-e",
                               f'display notification "{esc(body)}" with title "{esc(title)}"'],
                              capture_output=True, timeout=10)
        return done.returncode == 0
    except Exception:
        return False


def dashboard_port(sop_dir):
    """Configured dashboard port: $SMBOS_DASHBOARD_PORT, then triggers.json dashboard_port, else
    8765. Shared by the daemon, the app's cutover, and notification URLs so they always agree."""
    env = os.environ.get("SMBOS_DASHBOARD_PORT")
    if env and env.isdigit():
        return int(env)
    cfg = Path(sop_dir) / "triggers.json"
    if cfg.exists():
        try:
            v = json.loads(cfg.read_text(encoding="utf-8")).get("dashboard_port")
            if isinstance(v, int):
                return v
        except (OSError, ValueError):
            pass
    return 8765


def dashboard_url(sop_dir):
    """Stable local dashboard URL with its access token, what a notification click should open.

    Returns None if the token can't be read or created (e.g. an unwritable or vanished sop_dir).
    Callers pass it as an optional click target, and notify() is often called on error paths, so
    a token hiccup must not turn a clean 'needs attention' exit into a traceback."""
    try:
        return "http://127.0.0.1:{}/?t={}".format(dashboard_port(sop_dir), dashboard_token(sop_dir))
    except Exception:
        return None


def _flock(fd):
    import fcntl
    fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)


def acquire_run_lock(sop_dir, sop_id):
    """One concurrent run per SOP, across every entry point (dashboard, cron, CLI).

    flock on a persistent lockfile: the kernel releases it when the holder
    exits, however it exits, so there is no staleness, no pid parsing, and no
    reclaim protocol (a hand-rolled pid version had unfixable TOCTOU races;
    the race test caught two winners). The lockfile is never deleted: its
    presence means nothing, only the flock does. The pid/date written into it
    is diagnostic. Returns an opaque handle (keep it until release), or None
    if a live run holds the lock.
    """
    locks = Path(sop_dir) / "triggers"
    locks.mkdir(exist_ok=True)
    lock = locks / f"{sop_id}.lock"
    fd = os.open(lock, os.O_CREAT | os.O_RDWR)
    try:
        _flock(fd)
    except OSError:
        os.close(fd)
        return None
    os.ftruncate(fd, 0)
    os.write(fd, f"{os.getpid()} {date.today().isoformat()}\n".encode("utf-8"))
    return fd


def release_run_lock(lock):
    if lock is not None:
        try:
            os.close(lock)  # closing the fd releases the flock
        except OSError:
            pass


def run_lock_held(sop_dir, sop_id):
    """Is a live run holding this SOP's lock? (try-lock and immediately release)"""
    lock = Path(sop_dir) / "triggers" / f"{sop_id}.lock"
    if not lock.exists():
        return False
    fd = os.open(lock, os.O_RDWR)
    try:
        _flock(fd)
        return False  # we got it, so nobody holds it
    except OSError:
        return True
    finally:
        os.close(fd)


# --- Run gating + parked-result helpers --------------------------------------
# Relocated from serve_dashboard so both the legacy daemon and the FastAPI app
# share one implementation (the daemon now imports these). Pure: each takes a
# sop_dir plus arguments and touches only the library's own files; no daemon
# process state (LAUNCH_CWD etc.) leaks in, which is why these move cleanly and
# the stateful helpers (queue_run, append_suggestion, apply_item) do not yet.

def required_inputs(sop_dir, sid):
    """The SOP's `run_inputs:` frontmatter value (what a run must be given), or None.

    A run gate: an SOP that declares run_inputs cannot run until they're supplied. Resolves
    the SOP via find_sop (stem or frontmatter id, archive/runtime dirs skipped).
    """
    p = find_sop(sop_dir, sid)
    return frontmatter_field(p, "run_inputs") if p else None


def has_unrecorded_changes(sop_dir, sid):
    """True if the SOP file drifted from its recorded version (edited outside the save flow).

    A run gate: a drifted SOP must be reviewed/re-stamped before it runs, so a silent
    edit can't change what an unattended run does. Resolves the SOP via find_sop.
    """
    p = find_sop(sop_dir, sid)
    if p is None:
        return False
    meta, body = split_frontmatter(p.read_text(encoding="utf-8"))
    return is_drifted(meta, body)


def run_sop_command(sop_dir, sid, inputs=None, prepare=False, source="dashboard"):
    """The argv to spawn run_sop.py for one SOP run. Shared so the legacy daemon and the FastAPI
    app invoke the canonical runner IDENTICALLY (the cutover parity gate): both gate the request
    their own way, but the actual run goes through one command builder and one runner.
    """
    runner = Path(__file__).resolve().parent / "run_sop.py"
    cmd = [sys.executable, str(runner), sid, "--source", source, "--sop-dir", str(sop_dir)]
    if prepare:
        cmd.append("--prepare")
    if inputs:
        cmd += ["--inputs", str(inputs)[:2000]]
    return cmd


def resolve_pending_file(sop_dir, rel_name, decision):
    """Approve or discard a parked result (a `pending/` file awaiting the owner's call).

    Flips its `status: pending` frontmatter to approved/discarded and stamps a trailer.
    Returns the new status. Raises FileNotFoundError if the item is gone, ValueError on a
    bad decision. The basename is taken from rel_name so a path can't escape pending/.
    """
    p = Path(sop_dir) / "pending" / Path(str(rel_name)).name
    if not p.is_file():
        raise FileNotFoundError("no such pending item")
    if decision not in ("approve", "discard"):
        raise ValueError("decision must be approve or discard")
    text = p.read_text(encoding="utf-8")
    new_status = "approved" if decision == "approve" else "discarded"
    text = re.sub(r"^status: *pending$", f"status: {new_status}", text, count=1, flags=re.M)
    p.write_text(text + f"\n> {new_status} via dashboard on "
                 f"{datetime.now(timezone.utc).isoformat()}\n", encoding="utf-8")
    return new_status


def is_interactive_only(sop_dir, sid):
    """True if the SOP is `interactive_only` (needs a live-session connector, no headless run).

    A run gate: interactive_only SOPs are refused by the unattended runner, so the dashboard
    offers Pick up (an interactive session) instead of Run. Matches run_sop's truthy set.
    """
    p = find_sop(sop_dir, sid)
    if p is None:
        return False
    return (frontmatter_field(p, "interactive_only") or "").strip().lower() in ("true", "yes", "1")


def sop_declared_folder(sop_dir, sid):
    """An SOP's canonical `folder:` (expanded to an absolute path), or None.

    When set, queued tasks and launches for that SOP route there regardless of where the
    dashboard was launched (e.g. a client SOP always runs in its project folder).
    """
    match = next(iter(Path(sop_dir).rglob(f"{sid}.md")), None) if sid else None
    if match is None:
        return None
    raw = parse_frontmatter(match.read_text(encoding="utf-8")).get("folder")
    if not raw:
        return None
    folder = Path(os.path.expanduser(os.path.expandvars(raw.strip()))).resolve()
    return str(folder) if folder.is_dir() else None


def queue_run(sop_dir, sop_id, inputs=None, scope="here", launch_cwd=None):
    """Enqueue a run by writing a queue/ task file. Returns (sid, project folder).

    `launch_cwd` is the folder the dashboard was launched from (daemon process state, so it's
    passed in rather than read from a global). The run's project folder resolves as: explicit
    'anywhere' -> none; else the SOP's declared folder; else launch_cwd (unless it's home or the
    SOP dir, which mean 'no particular project'); else none.
    """
    sid = re.sub(r"[^a-z0-9-]", "", str(sop_id).lower())
    if not sid or not any(Path(sop_dir).rglob(f"{sid}.md")):
        raise ValueError("unknown task")
    qdir = Path(sop_dir) / "queue"
    qdir.mkdir(exist_ok=True)
    now = datetime.now(timezone.utc)
    declared = sop_declared_folder(sop_dir, sid)
    if scope == "anywhere":
        project = ""  # owner explicitly chose any folder
    elif declared:
        project = declared  # the SOP knows its home (e.g. a client SOP -> its project folder)
    elif not launch_cwd or launch_cwd in (str(Path.home()), str(sop_dir)):
        project = ""
    else:
        project = launch_cwd
    body = (f"---\nsop: {sid}\nrequested: {now.isoformat()}\nsource: dashboard\n"
            f"project: {project}\nstatus: queued\n---\n")
    if inputs:
        body += f"\nOwner's notes for the run:\n{str(inputs)[:2000]}\n"
    (qdir / f"{now.strftime('%Y%m%dT%H%M%S')}-{sid}.md").write_text(body, encoding="utf-8")
    return sid, project


def append_suggestion(sop_dir, rel_path, text):
    """Append a one-line owner suggestion to an SOP's "Notes for next revision" section.

    `rel_path` must resolve INSIDE sop_dir and name a real .md SOP (not the index/template);
    a path that escapes raises PermissionError, a non-SOP raises FileNotFoundError.
    """
    root = Path(sop_dir).resolve()
    target = (root / rel_path).resolve()
    try:
        target.relative_to(root)
    except ValueError:
        raise PermissionError("path escapes the SOP directory")
    if target.suffix != ".md" or target.name in SKIP_NAMES or not target.is_file():
        raise FileNotFoundError("not an SOP file")
    bullet = "- ({}, via dashboard) {}".format(date.today().isoformat(), " ".join(text.split()))
    content = target.read_text(encoding="utf-8")
    if NOTES_HEADING in content:
        head, _, tail = content.partition(NOTES_HEADING)
        nxt = tail.find("\n## ")
        if nxt == -1:
            content = head + NOTES_HEADING + tail.rstrip() + "\n" + bullet + "\n"
        else:
            section, rest = tail[:nxt], tail[nxt:]
            content = head + NOTES_HEADING + section.rstrip() + "\n" + bullet + "\n" + rest
    else:
        block = "\n" + NOTES_HEADING + "\n\n" + bullet + "\n"
        cl = content.find("\n## Changelog")
        if cl == -1:
            content = content.rstrip() + "\n" + block
        else:
            content = content[:cl] + block + content[cl:]
    target.write_text(content, encoding="utf-8")


# --- Run-lifecycle markers ---------------------------------------------------
# The flock says "a run is live" only while the holder is alive: a crashed or
# killed run releases its lock, leaving no trace (the silent-failure class).
# A marker file written at run start and cleared at every graceful exit makes
# all three states visible. Liveness is judged by the run lock, not the pid:
# the kernel releases the flock the instant the holder exits, whereas os.kill(0)
# still succeeds for zombies and reused pids. So: marker + lock held = running;
# marker + lock free (or too old to be a legitimate live run) = stopped without
# finishing; no marker = idle/done. A hard kill leaves the marker behind on
# purpose, releases the lock, and so reads as stopped, which is how the death shows.
_RUN_STALE_AFTER_S = 1200  # backstop past the 900s subprocess timeout + overhead


def _active_dir(sop_dir):
    return Path(sop_dir) / "active-runs"


def mark_run_active(sop_dir, sop_id, mode="triggered", source="manual"):
    """Record that a run of sop_id started. Returns the marker path (keep it,
    pass to clear_run_active at the end). Supersedes any prior marker for the
    same SOP so a fresh run clears a stale one."""
    d = _active_dir(sop_dir)
    d.mkdir(exist_ok=True)
    for old in d.glob(f"{sop_id}__*.json"):
        try:
            old.unlink()
        except OSError:
            pass
    marker = d / f"{sop_id}__{os.getpid()}.json"
    marker.write_text(json.dumps({"sop": sop_id, "pid": os.getpid(),
                                  "started": datetime.now(timezone.utc).isoformat(),
                                  "mode": mode, "source": source}), encoding="utf-8")
    return marker


def clear_run_active(marker):
    if not marker:
        return
    try:
        Path(marker).unlink()
    except OSError:
        pass


def active_runs(sop_dir):
    """Read-only: in-flight run markers, classified. Returns a list of
    {sop, file, started, mode, source, state} where state is 'running' or
    'stalled' (started but stopped without finishing). Safe to call from a GET."""
    d = _active_dir(sop_dir)
    if not d.is_dir():
        return []
    now = datetime.now(timezone.utc)
    out = []
    for p in sorted(d.glob("*.json")):
        try:
            m = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        try:
            age = (now - datetime.fromisoformat(m.get("started"))).total_seconds()
        except (ValueError, TypeError):
            age = _RUN_STALE_AFTER_S + 1
        # The held flock is authoritative: it is released the moment the runner
        # exits, so a zombie / reused pid can't masquerade as running.
        running = age <= _RUN_STALE_AFTER_S and run_lock_held(sop_dir, m.get("sop", ""))
        out.append({"sop": m.get("sop", p.stem), "file": p.name,
                    "started": m.get("started"), "mode": m.get("mode", ""),
                    "source": m.get("source", ""),
                    "state": "running" if running else "stalled"})
    return out


def append_run(sop_dir, record):
    with (Path(sop_dir) / "runs.jsonl").open("a", encoding="utf-8") as f:
        f.write(json.dumps(record) + "\n")


def dashboard_token(sop_dir):
    """Read the dashboard's shared access token, creating it (0600) on first use.

    Lives in <sop_dir>/.dashboard-token so the local dashboard server(s) can gate their
    endpoints. The single source of truth for the token, both the legacy daemon and the
    FastAPI app call this so they always agree. Creation is atomic (O_CREAT|O_EXCL): if two
    processes start against a fresh dir at once, exactly one writes and the rest read the
    winner's token, so they never mint divergent tokens. The file is gitignored.
    """
    path = Path(sop_dir) / ".dashboard-token"
    existing = _read_token(path)
    if existing:
        return existing
    token = secrets.token_urlsafe(32)
    try:
        fd = os.open(str(path), os.O_CREAT | os.O_EXCL | os.O_WRONLY, stat.S_IRUSR | stat.S_IWUSR)
    except FileExistsError:
        # Another process won the create race. The file exists but is briefly EMPTY until the
        # winner writes, so poll for the written token rather than minting our own (which would
        # re-introduce divergent tokens, the exact bug O_EXCL is meant to prevent).
        for _ in range(100):  # ~1s ceiling; the winner writes within milliseconds
            existing = _read_token(path)
            if existing:
                return existing
            time.sleep(0.01)
        return _read_token(path) or token  # winner created but never wrote (e.g. crashed mid-create)
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(token)
    return token


def _read_token(path):
    try:
        return path.read_text(encoding="utf-8").strip()
    except OSError:
        return ""
