"""Shared SmbOS helpers: directory resolution, frontmatter, SOP iteration, run log.

The canonical implementations; scripts import from here instead of re-rolling.
Stdlib only, Python 3.9+ (the macOS system python that Claude Desktop uses).
"""
import hashlib
import json
import os
import re
import sys
from datetime import date, datetime, timezone
from pathlib import Path

SKIP_NAMES = {"INDEX.md", "_template.md", "DIGEST.md"}  # DIGEST.md is generated by digest.py
# Directories under the SOP root that hold runtime state, never SOPs.
RUNTIME_DIRS = {"pending", "payloads", "triggers", "queue", "work", "active-runs"}
ARCHIVE_DIR = "archive"


def resolve_sop_dir(explicit=None, use_cwd=False, exit_on_missing=True):
    """argv-style explicit > $SOP_DIR > (optionally ./sops) > ~/sops."""
    candidates = [explicit, os.environ.get("SOP_DIR")]
    if use_cwd:
        candidates.append(str(Path.cwd() / "sops"))
    candidates.append(str(Path.home() / "sops"))
    for c in candidates:
        if c and Path(c).expanduser().is_dir():
            return Path(c).expanduser()
    if exit_on_missing:
        sys.exit("No SOP directory found (checked explicit, $SOP_DIR, ~/sops).")
    return None


def parse_frontmatter(text):
    """Return the frontmatter dict from a markdown document ('' values stripped)."""
    meta = {}
    m = re.match(r"^---\r?\n(.*?)\r?\n---", text, re.S)
    if m:
        for line in m.group(1).splitlines():
            if ":" in line and not line.lstrip().startswith("#"):
                k, _, v = line.partition(":")
                meta[k.strip()] = v.strip()
    return meta


def split_frontmatter(text):
    """Return (meta dict, body) for a markdown document."""
    m = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n?(.*)$", text, re.S)
    if not m:
        return {}, text
    meta = parse_frontmatter(text)
    return meta, m.group(2)


# Sections that are journals about the procedure, not the procedure itself.
# Excluded from the fingerprint so dashboard suggestions and changelog lines
# never read as unrecorded changes.
_JOURNAL_SECTIONS = ("Notes for next revision", "Changelog")


# Frontmatter fields that grant capabilities to background runs. They MUST be
# inside the fingerprint: the stamp is what makes them owner-sanctioned, and a
# body-only hash would let an out-of-band edit widen the allowlist of an
# already-stamped SOP without tripping the drift gate.
CAPABILITY_FIELDS = ("research_domains", "research_reads", "deliverable")


def content_fingerprint(body, meta=None):
    """Hash of the procedure: body (journal sections stripped, line endings
    normalized) plus the capability-granting frontmatter fields."""
    text = body.replace("\r\n", "\n")
    for name in _JOURNAL_SECTIONS:
        text = re.sub(rf"^## {re.escape(name)}\n.*?(?=^## |\Z)", "", text, flags=re.M | re.S)
    m = meta or {}
    caps = "\n".join(f"{k}={m.get(k, '')}" for k in CAPABILITY_FIELDS)
    # interactive_only is capability-bearing (it gates the unattended runner),
    # so fold it into the fingerprint to make stripping it out-of-band trip
    # drift detection. Append only when set, so adding this never re-fingerprints
    # the existing stamped SOPs that don't carry the flag.
    if str(m.get("interactive_only", "")).strip().lower() in ("true", "yes", "1"):
        caps += "\ninteractive_only=true"
    return hashlib.sha256((caps + "\n" + text.strip()).encode("utf-8")).hexdigest()[:12]


def is_drifted(meta, body):
    """True when the body no longer matches the recorded fingerprint.

    A missing fingerprint is "unstamped", not drift: existing libraries
    stay quiet until their SOPs are stamped or bumped.
    """
    recorded = meta.get("content_hash")
    return bool(recorded) and recorded != content_fingerprint(body, meta)


def set_frontmatter_fields(text, updates):
    """Upsert frontmatter fields, preserving order; new fields go before the closing ---."""
    m = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n?(.*)$", text, re.S)
    if not m:
        raise ValueError("document has no frontmatter")
    lines = m.group(1).splitlines()
    pending = dict(updates)
    for i, line in enumerate(lines):
        k = line.partition(":")[0].strip()
        if k in pending:
            lines[i] = f"{k}: {pending.pop(k)}"
    lines += [f"{k}: {v}" for k, v in pending.items()]
    return "---\n" + "\n".join(lines) + "\n---\n" + m.group(2)


def frontmatter_field(path, field, head_bytes=1000):
    """Read one frontmatter field from a file without parsing the whole document."""
    head = Path(path).read_text(encoding="utf-8")[:head_bytes]
    m = re.search(rf"^{re.escape(field)}: *(.+)$", head, re.M)
    return m.group(1).strip() if m else None


def iter_sops(sop_dir, include_archive=False):
    """Yield SOP file paths, skipping runtime dirs, index, template, dotfiles."""
    skip = set(RUNTIME_DIRS) if include_archive else set(RUNTIME_DIRS) | {ARCHIVE_DIR}
    for p in sorted(Path(sop_dir).rglob("*.md")):
        rel = p.relative_to(sop_dir)
        if p.name in SKIP_NAMES or p.name.startswith(".") or any(d in skip for d in rel.parts):
            continue
        yield p


def find_sop(sop_dir, sop_id):
    """Find an SOP by filename stem or frontmatter id; None if absent."""
    for p in iter_sops(sop_dir):
        if p.stem == sop_id:
            return p
        if frontmatter_field(p, "id") == sop_id:
            return p
    return None


def read_runs(sop_dir):
    """Parse runs.jsonl into a list of dicts, skipping malformed lines."""
    log = Path(sop_dir) / "runs.jsonl"
    out = []
    if log.exists():
        for line in log.read_text(encoding="utf-8").splitlines():
            try:
                out.append(json.loads(line))
            except ValueError:
                continue
    return out


def month_spend(sop_dir):
    """Sum cost_usd of this calendar month's runs."""
    prefix = date.today().strftime("%Y-%m")
    total = 0.0
    for r in read_runs(sop_dir):
        if str(r.get("ts", "")).startswith(prefix):
            try:
                total += float(r.get("cost_usd") or 0)
            except (TypeError, ValueError):
                continue
    return total


def notify(title, body):
    """macOS notification; silent no-op elsewhere and on any failure."""
    if sys.platform != "darwin":
        return False
    esc = lambda s: str(s).replace("\\", "\\\\").replace('"', '\\"')
    try:
        import subprocess
        done = subprocess.run(["/usr/bin/osascript", "-e",
                               f'display notification "{esc(body)}" with title "{esc(title)}"'],
                              capture_output=True, timeout=10)
        return done.returncode == 0
    except (OSError, Exception):
        return False


def _flock(fd):
    import fcntl
    fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)


def acquire_run_lock(sop_dir, sop_id):
    """One concurrent run per SOP, across every entry point (dashboard, cron, CLI).

    flock on a persistent lockfile: the kernel releases it when the holder
    exits, however it exits, so there is no staleness, no pid parsing, and no
    reclaim protocol (a hand-rolled pid version had unfixable TOCTOU races;
    the race test caught two winners). The lockfile is never deleted: its
    presence means nothing, only the flock does. The pid/date written into it
    is diagnostic. Returns an opaque handle (keep it until release), or None
    if a live run holds the lock.
    """
    locks = Path(sop_dir) / "triggers"
    locks.mkdir(exist_ok=True)
    lock = locks / f"{sop_id}.lock"
    fd = os.open(lock, os.O_CREAT | os.O_RDWR)
    try:
        _flock(fd)
    except OSError:
        os.close(fd)
        return None
    os.ftruncate(fd, 0)
    os.write(fd, f"{os.getpid()} {date.today().isoformat()}\n".encode("utf-8"))
    return fd


def release_run_lock(lock):
    if lock is not None:
        try:
            os.close(lock)  # closing the fd releases the flock
        except OSError:
            pass


def run_lock_held(sop_dir, sop_id):
    """Is a live run holding this SOP's lock? (try-lock and immediately release)"""
    lock = Path(sop_dir) / "triggers" / f"{sop_id}.lock"
    if not lock.exists():
        return False
    fd = os.open(lock, os.O_RDWR)
    try:
        _flock(fd)
        return False  # we got it, so nobody holds it
    except OSError:
        return True
    finally:
        os.close(fd)


# --- Run-lifecycle markers ---------------------------------------------------
# The flock says "a run is live" only while the holder is alive: a crashed or
# killed run releases its lock, leaving no trace (the silent-failure class).
# A marker file written at run start and cleared at every graceful exit makes
# all three states visible. Liveness is judged by the run lock, not the pid:
# the kernel releases the flock the instant the holder exits, whereas os.kill(0)
# still succeeds for zombies and reused pids. So: marker + lock held = running;
# marker + lock free (or too old to be a legitimate live run) = stopped without
# finishing; no marker = idle/done. A hard kill leaves the marker behind on
# purpose, releases the lock, and so reads as stopped, which is how the death shows.
_RUN_STALE_AFTER_S = 1200  # backstop past the 900s subprocess timeout + overhead


def _active_dir(sop_dir):
    return Path(sop_dir) / "active-runs"


def mark_run_active(sop_dir, sop_id, mode="triggered", source="manual"):
    """Record that a run of sop_id started. Returns the marker path (keep it,
    pass to clear_run_active at the end). Supersedes any prior marker for the
    same SOP so a fresh run clears a stale one."""
    d = _active_dir(sop_dir)
    d.mkdir(exist_ok=True)
    for old in d.glob(f"{sop_id}__*.json"):
        try:
            old.unlink()
        except OSError:
            pass
    marker = d / f"{sop_id}__{os.getpid()}.json"
    marker.write_text(json.dumps({"sop": sop_id, "pid": os.getpid(),
                                  "started": datetime.now(timezone.utc).isoformat(),
                                  "mode": mode, "source": source}), encoding="utf-8")
    return marker


def clear_run_active(marker):
    if not marker:
        return
    try:
        Path(marker).unlink()
    except OSError:
        pass


def active_runs(sop_dir):
    """Read-only: in-flight run markers, classified. Returns a list of
    {sop, file, started, mode, source, state} where state is 'running' or
    'stalled' (started but stopped without finishing). Safe to call from a GET."""
    d = _active_dir(sop_dir)
    if not d.is_dir():
        return []
    now = datetime.now(timezone.utc)
    out = []
    for p in sorted(d.glob("*.json")):
        try:
            m = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
        try:
            age = (now - datetime.fromisoformat(m.get("started"))).total_seconds()
        except (ValueError, TypeError):
            age = _RUN_STALE_AFTER_S + 1
        # The held flock is authoritative: it is released the moment the runner
        # exits, so a zombie / reused pid can't masquerade as running.
        running = age <= _RUN_STALE_AFTER_S and run_lock_held(sop_dir, m.get("sop", ""))
        out.append({"sop": m.get("sop", p.stem), "file": p.name,
                    "started": m.get("started"), "mode": m.get("mode", ""),
                    "source": m.get("source", ""),
                    "state": "running" if running else "stalled"})
    return out


def append_run(sop_dir, record):
    with (Path(sop_dir) / "runs.jsonl").open("a", encoding="utf-8") as f:
        f.write(json.dumps(record) + "\n")
